# Generated by Django 4.1.7 on 2023-03-18 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancillaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='cancillaria', max_length=120, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.FloatField(default=10, verbose_name='Цена')),
                ('date_add', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('date_update', models.DateField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('photo', models.ImageField(null=True, upload_to='image/%Y/%m/%d', verbose_name='Фотография')),
                ('exist', models.BooleanField(default=True, verbose_name='В каталоге ?')),
            ],
            options={
                'verbose_name': 'канцтовар',
                'verbose_name_plural': 'Канцтовары',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('date_finish', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения заказа')),
                ('price', models.FloatField(null=True, verbose_name='Стоимость заказа')),
                ('address_delivery', models.CharField(max_length=150, verbose_name='Адрес доставки')),
                ('status', models.CharField(choices=[('1', 'Создан'), ('2', 'Отменён'), ('3', 'Согласован'), ('4', 'В пути'), ('5', 'Завершён')], max_length=150, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['date_create'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название поставщика')),
                ('agent_name', models.CharField(max_length=100, verbose_name='Имя агента поставщика')),
                ('agent_firstname', models.CharField(max_length=100, verbose_name='Фамилия агента поставщика')),
                ('agent_patronymic', models.CharField(max_length=100, verbose_name='Отчество агента поставщика')),
                ('exist', models.BooleanField(default=True, verbose_name='Сотрудничаем?')),
            ],
            options={
                'verbose_name': 'поставщика',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Chegue',
            fields=[
                ('date_print', models.DateTimeField(auto_now_add=True, verbose_name='Дата распечатки')),
                ('address_print', models.CharField(max_length=150, verbose_name='Место создания чека')),
                ('terminal', models.CharField(max_length=10, verbose_name='Код терминала')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='cancillaria.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'чек',
                'verbose_name_plural': 'Чеки',
                'ordering': ['terminal', 'date_print'],
            },
        ),
        migrations.CreateModel(
            name='Pos_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_cancillaria', models.IntegerField(verbose_name='Количество книг')),
                ('price', models.FloatField(verbose_name='Общая цена книг')),
                ('cancillaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cancillaria.cancillaria', verbose_name='Книга')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cancillaria.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'позицию',
                'verbose_name_plural': 'Позиции',
                'ordering': ['cancillaria', 'order', 'price'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='cancillarias',
            field=models.ManyToManyField(through='cancillaria.Pos_order', to='cancillaria.cancillaria'),
        ),
        migrations.AddField(
            model_name='cancillaria',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cancillaria.supplier', verbose_name='Поставщик'),
        ),
    ]
