# Generated by Django 4.1.7 on 2023-03-21 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cancillaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chegue',
            options={'ordering': ['terminal', 'date_print'], 'verbose_name': 'чек', 'verbose_name_plural': 'Чек'},
        ),
        migrations.AlterModelOptions(
            name='pos_order',
            options={'ordering': ['cancillaria', 'order', 'price'], 'verbose_name': 'позицию', 'verbose_name_plural': 'Позиции заказа'},
        ),
        migrations.AlterField(
            model_name='cancillaria',
            name='photo',
            field=models.ImageField(null=True, upload_to='image/%Y/%m/%d', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='pos_order',
            name='cancillaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cancillaria.cancillaria', verbose_name='Канцтовар'),
        ),
        migrations.AlterField(
            model_name='pos_order',
            name='count_cancillaria',
            field=models.IntegerField(verbose_name='Количество кантовара'),
        ),
        migrations.AlterField(
            model_name='pos_order',
            name='price',
            field=models.FloatField(verbose_name='Общая цена канцтовара'),
        ),
    ]
